FROM tomcat:9-jdk17
# remove default ROOT
RUN rm -rf /usr/local/tomcat/webapps/ROOT
# copy war (ensure you build the war before docker build)
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war
# change Tomcat port from 8080 to 9090
RUN sed -i 's/port="8080"/port="9090"/g' /usr/local/tomcat/conf/server.xml
EXPOSE 9090
CMD ["catalina.sh", "run"]
